### PR TITLE
Make the relationship weight editable.

### PR DESCRIPTION
**Pull request by ovista-dept**

### CODE REVIEW

**Review by mlsamuelson — CHANGES_REQUESTED** [review]
I was testing in the CI test site and the fields look good, but the save changes link only shows up when I re-order through drag and drop, so if I edit the order manually, I have no way to save. Can you resolve that? Thank you.

**Comment by mlsamuelson** [comment]
@ovista-dept Circling back around to check on the status of this, when you're able to address it.

**Comment by ovista-dept** [comment]
I removed the debug that was breaking the code.

**Review by mlsamuelson — APPROVED** [review]

**Comment by ovista-dept** [comment]
Created a new PR for Sprint-8

**Pull request closed without merging**
